AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create AWS DMS resources for migrating data between databases

Parameters:
  EnvType:
    Type: String
    Default: "dev"
    Description: The environment type (e.g., prod, dev)

  DomainName:
    Type: String
    Description: The name of the domain

  MySQLUsername:
    Type: String
    Description: MySQLUsername

  MySQLPassword:
    Type: String
    NoEcho: true
    Description: MySQLPassword

  PostgreSQLUsername:
    Type: String
    Description: PostgreSQLUsername

  PostgreSQLPassword:
    Type: String
    NoEcho: true
    Description: PostgreSQLPassword

Resources:
  DMSVPCRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-dms-vpc-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: dms.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole

  DMSReplicationInstance:
    Type: AWS::DMS::ReplicationInstance
    Properties: 
      ReplicationInstanceClass: dms.r5.large
      AllocatedStorage: 100
      ReplicationInstanceIdentifier: !Sub "${EnvType}-${DomainName}-instance"
      PubliclyAccessible: false
      VpcSecurityGroupIds: 
        - sg-0e9f469431b6b03bf  # Replace with your security group ID
      AvailabilityZone: us-east-1a
      ReplicationSubnetGroupIdentifier: !Ref DMSReplicationSubnetGroup

  DMSReplicationSubnetGroup:
    Type: AWS::DMS::ReplicationSubnetGroup
    DependsOn: DMSVPCRole
    Properties:
      ReplicationSubnetGroupIdentifier: !Sub "${AWS::StackName}-subnet-group"
      ReplicationSubnetGroupDescription: "Subnet group for DMS replication"
      SubnetIds:
        - subnet-0ded02dc4c9cf6fca  # Replace with your subnet IDs
        - subnet-072b15917378e74df
        - subnet-03d30d1b1121cdb69

  DMSSourceEndpoint:
    Type: AWS::DMS::Endpoint
    Properties: 
      EndpointIdentifier: !Sub "${AWS::StackName}-source-endpoint"
      EndpointType: source
      EngineName: mysql
      Username: !Ref MySQLUsername
      Password: !Ref MySQLPassword
      ServerName: my-source-db.example.com  # Replace with actual MySQL host
      Port: 3306
      DatabaseName: my-source-database  # Replace with actual MySQL DB name

  DMSTargetEndpoint:
    Type: AWS::DMS::Endpoint
    Properties: 
      EndpointIdentifier: !Sub "${AWS::StackName}-target-endpoint"
      EndpointType: target
      EngineName: postgres
      Username: !Ref PostgreSQLUsername
      Password: !Ref PostgreSQLPassword
      ServerName: my-target-db.example.com  # Replace with actual PostgreSQL host
      Port: 5432
      DatabaseName: my-target-database  # Replace with actual PostgreSQL DB name

  DMSMigrationTask:
    Type: AWS::DMS::ReplicationTask
    Properties: 
      ReplicationTaskIdentifier: !Sub "${AWS::StackName}-migration-task"
      SourceEndpointArn: !Ref DMSSourceEndpoint
      TargetEndpointArn: !Ref DMSTargetEndpoint
      ReplicationInstanceArn: !Ref DMSReplicationInstance
      MigrationType: full-load
      TableMappings: 
        {
          "rules": [
            {
              "rule-type": "selection",
              "rule-id": "1",
              "rule-name": "1",
              "object-locator": {
                "schema-name": "%", 
                "table-name": "%"
              },
              "rule-action": "include"
            }
          ]
        }

Outputs:
  ReplicationInstanceArn:
    Description: "The ARN of the DMS replication instance"
    Value: !Ref DMSReplicationInstance

  SourceEndpointArn:
    Description: "The ARN of the source endpoint"
    Value: !Ref DMSSourceEndpoint

  TargetEndpointArn:
    Description: "The ARN of the target endpoint"
    Value: !Ref DMSTargetEndpoint

  MigrationTaskArn:
    Description: "The ARN of the DMS migration task"
    Value: !Ref DMSMigrationTask