AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nested stack for creating a DynamoDB table'

Parameters:
  EnvType:
    Type: String
    Default: "dev"
    Description: The environment type (e.g., prod, dev)
  DomainName:
    Type: String
    Description: The name of the domain
  ReadCapacityUnits:
    Type: Number
    Description: 'Read capacity units for the table'
  WriteCapacityUnits:
    Type: Number
    Description: 'Write capacity units for the table'

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
            Fn::Join:
            - "-"
            - [ "tpgt", !Ref DomainName, !Ref EnvType, "landing", "table"]
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'sortKey'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
        - AttributeName: 'sortKey'
          KeyType: 'RANGE'
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits
      Tags:
        - Key: 'Environment'
          Value: 'Dev'

Outputs:
  TableName:
    Description: 'Name of the created DynamoDB table'
    Value: !Ref DynamoDBTable
