AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Parameters:
#S3 Parameters  
  EnvType:
    Type: String
    Default: "dev"
    Description: The environment type (e.g., prod, dev)
  DomainName:
    Type: String
    Description: The name of the domain
  BucketFilePath:
    Type: String
    Description: bucket yaml path
#GlueDB Parameters
  DatabaseName:
    Type: String
    Default: 'tpg-glue-db'  
    Description: 'Name of the Glue Database'
  GlueDBPath:
    Type: String
    Description: Database yaml path    

#Crawler Parameters
  CrawlerName:
    Type: String
    Default: 'tpg-glue-crawler'
    Description: 'Name of the Glue Crawler'
  GlueCrawlerPath:
    Type: String
    Description: Crawler yaml path    

#Dynamo DB Parameters
  TableName:
    Type: String
    Description: 'Name of the DynamoDB table'
    Default: 'tpg-dynamodb-table'
  ReadCapacityUnits:
    Type: Number
    Description: 'Read capacity units for the table'
    Default: 5
    MinValue: 1
  WriteCapacityUnits:
    Type: Number
    Description: 'Write capacity units for the table'
    Default: 5
    MinValue: 1
  DynamoDBStackUrl:
    Type: String
    Description: 'Dynamo DB S3 URL of the nested stack template'

  #Redshift Parameters
  RedshiftiamRoleUrl:
    Type: String
    Description: 'Name of the Redshift Iam Role'

  #Redshift Subnet Parameters
  VpcCidr:
    Description: CIDR block for the VPC
    Type: String
    Default: 10.0.0.0/16

  PublicSubnet1Cidr:
    Description: CIDR block for the first public subnet
    Type: String
    Default: 10.0.1.0/24

  PublicSubnet2Cidr:
    Description: CIDR block for the second public subnet
    Type: String
    Default: 10.0.2.0/24

  PublicSubnet3Cidr:
    Description: CIDR block for the second public subnet
    Type: String
    Default: 10.0.3.0/24

  PrivateSubnet1Cidr:
    Description: CIDR block for the first private subnet
    Type: String
    Default: 10.0.4.0/27

  PrivateSubnet2Cidr:
    Description: CIDR block for the second private subnet
    Type: String
    Default: 10.0.5.0/27

  PrivateSubnet3Cidr:
    Description: CIDR block for the second private subnet
    Type: String
    Default: 10.0.6.0/27

  AvailabilityZone1:
    Description: First Availability Zone for subnets
    Type: String
    Default: us-east-1a

  AvailabilityZone2:
    Description: Second Availability Zone for subnets
    Type: String
    Default: us-east-1b

  AvailabilityZone3:
    Description: Second Availability Zone for subnets
    Type: String
    Default: us-east-1c 

  RedshiftVPCStackUrl:
    Type: String
    Description: 'Name of the VPC stack'

  #Redshift Serverless Parameters
  NamespaceName:
    Description: Name for the Redshift Serverless namespace
    Type: String
    Default: my-serverless-namespace
    AllowedPattern: '^[a-zA-Z0-9-]+$'
    MinLength: 3
    MaxLength: 64
    ConstraintDescription: Must be a valid namespace name.

  WorkgroupName:
    Description: Name for the Redshift Serverless workgroup
    Type: String
    Default: my-serverless-workgroup
    AllowedPattern: '^[a-zA-Z0-9-]+$'
    MinLength: 3
    MaxLength: 64
    ConstraintDescription: Must be a valid workgroup name.

  DatabaseName:
    Description: Name of the database in the Redshift Serverless namespace
    Type: String
    Default: mydatabase
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9]*$'
    MinLength: 1
    MaxLength: 127
    ConstraintDescription: Must be alphanumeric and start with a letter.

  AdminUsername:
    Description: Master username for the Redshift Serverless database
    Type: String
    Default: admin
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9]*$'
    MinLength: 1
    MaxLength: 128
    ConstraintDescription: Must begin with a letter and be alphanumeric.

  AdminUserPassword:
    Description: Master password for the Redshift Serverless database
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 64
    Default: Admin1234567
    AllowedPattern: '[a-zA-Z0-9!@#$%^&*()_+=-]*'
    ConstraintDescription: Must contain alphanumeric characters and symbol.

  # VPCSecurityGroupIds:
  #   Description: Comma-separated list of security group IDs
  #   Type: CommaDelimitedList
  #   Default: !Ref SecurityGroupId
    
  # SubnetIds:
  #   Description: Comma-separated list of subnet IDs for the Redshift Serverless workgroup
  #   Type: CommaDelimitedList
  #   Default: !Join [ ",", [ !Ref PublicSubnet1Id, !Ref PublicSubnet2Id, !Ref PublicSubnet3Id ] ] 
    
  RedshiftServerlessStackUrl:
    Type: String
    Description: 'Name of the VPC stack'  
      

Resources:
  s3buckets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref BucketFilePath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName

  GlueDatabase:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref GlueDBPath
      Parameters:
        DatabaseName: !Ref DatabaseName

  GlueCrawler:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref GlueCrawlerPath
      Parameters:
        CrawlerName: !Ref CrawlerName
        DatabaseName: !GetAtt GlueDatabase.Outputs.DatabaseName
        S3TargetPath: !GetAtt s3buckets.Outputs.LandingBucketName

  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref DynamoDBStackUrl
      Parameters:
        TableName: !Ref TableName
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits

  RedshiftiamRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref RedshiftiamRoleUrl  

  RedshiftVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref RedshiftVPCStackUrl
      Parameters:
        VpcCidr: !Ref VpcCidr
        PublicSubnet1Cidr: !Ref PublicSubnet1Cidr
        PublicSubnet2Cidr: !Ref PublicSubnet2Cidr
        PublicSubnet3Cidr: !Ref PublicSubnet3Cidr
        PrivateSubnet1Cidr: !Ref PrivateSubnet1Cidr
        PrivateSubnet2Cidr: !Ref PrivateSubnet2Cidr
        PrivateSubnet3Cidr: !Ref PrivateSubnet3Cidr
        AvailabilityZone1: !Ref AvailabilityZone1
        AvailabilityZone2: !Ref AvailabilityZone2
        AvailabilityZone3: !Ref AvailabilityZone3  

  RedshiftServerlessStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref RedshiftServerlessStackUrl
      Parameters:
        NamespaceName: !Ref NamespaceName
        WorkgroupName: !Ref WorkgroupName
        DatabaseName: !Ref DatabaseName
        AdminUsername: !Ref AdminUsername
        AdminUserPassword: !Ref AdminUserPassword
        # VPCSecurityGroupIds: !Ref VPCSecurityGroupIds
        # SubnetIds: !Ref SubnetIds        

Outputs:
  LandingBucketName:
    Description: The name of the Landing S3 bucket
    Value: !GetAtt s3buckets.Outputs.LandingBucketName
  RawS3BucketName:
    Description: The name of the Raw S3 bucket
    Value: !GetAtt s3buckets.Outputs.RawS3BucketName
  EnrichedS3BucketName:
    Description: The name of the Enriched S3 bucket
    Value: !GetAtt s3buckets.Outputs.EnrichedS3BucketName
  DatabaseName:
    Description: 'Name of the Glue Database'
    Value:  !GetAtt GlueDatabase.Outputs.DatabaseName
  CrawlerName:
    Description: 'Name of the created Glue Crawler'
    Value:  !GetAtt GlueCrawler.Outputs.CrawlerName
  TableName:
    Description: 'Name of the created DynamoDB table'
    Value: !GetAtt DynamoDBStack.Outputs.TableName
  RedshiftIamRoleName:
    Description: 'Name of the created Redshift IAM role'
    Value: !GetAtt RedshiftiamRoleStack.Outputs.RedshiftIamRoleName
  VpcId:
    Description: 'The VPC ID'
    Value: !GetAtt RedshiftVPCStack.Outputs.VpcId
  PublicSubnet1Id:
    Description: 'The ID of the first public subnet'
    Value: !GetAtt RedshiftVPCStack.Outputs.PublicSubnet1Id
  PublicSubnet2Id:
    Description: 'The ID of the second public subnet'
    Value: !GetAtt RedshiftVPCStack.Outputs.PublicSubnet2Id
  PublicSubnet3Id:
    Description: 'The ID of the third public subnet'
    Value: !GetAtt RedshiftVPCStack.Outputs.PublicSubnet3Id
  PrivateSubnet1Id:
    Description: 'The ID of the first private subnet'
    Value: !GetAtt RedshiftVPCStack.Outputs.PrivateSubnet1Id
  PrivateSubnet2Id:
    Description: 'The ID of the second private subnet'
    Value: !GetAtt RedshiftVPCStack.Outputs.PrivateSubnet2Id
  PrivateSubnet3Id:
    Description: 'The ID of the third private subnet'
    Value: !GetAtt RedshiftVPCStack.Outputs.PrivateSubnet3Id
  SecurityGroupId:
    Description: 'The ID of the Redshift Security Group'
    Value: !GetAtt RedshiftVPCStack.Outputs.SecurityGroupId
  WorkgroupEndpoint:
    Description: 'The endpoint of the Redshift Serverless workgroup'
    Value: !GetAtt RedshiftServerlessStack.Outputs.WorkgroupEndpoint                    


