AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket

Parameters:
#IAMRole Parameters
  IamRoleUrl:
    Type: String
    Description: 'Name of the IAM Role Url' 
#S3 Parameters  
  EnvType:
    Type: String
    Default: "dev"
    Description: The environment type (e.g., prod, dev)
  DomainName:
    Type: String
    Default: "finance"
    Description: The name of the domain
  BucketFilePath:
    Type: String
    Description: bucket yaml path
#GlueDB Parameters
  GlueDBPath:
    Type: String
    Description: Database yaml path    

#Crawler Parameters
  GlueCrawlerPath:
    Type: String
    Description: Crawler yaml path    

#Dynamo DB Parameters
  ReadCapacityUnits:
    Type: Number
    Description: 'Read capacity units for the table'
    Default: 5
    MinValue: 1
  WriteCapacityUnits:
    Type: Number
    Description: 'Write capacity units for the table'
    Default: 5
    MinValue: 1
  DynamoDBStackUrl:
    Type: String
    Description: 'Dynamo DB S3 URL of the nested stack template'

  #Redshift Subnet Parameters
  VpcCidr:
    Description: CIDR block for the VPC
    Type: String
    Default: 10.0.0.0/16

  PublicSubnet1Cidr:
    Description: CIDR block for the first public subnet
    Type: String
    Default: 10.0.1.0/24

  PublicSubnet2Cidr:
    Description: CIDR block for the second public subnet
    Type: String
    Default: 10.0.2.0/24

  PublicSubnet3Cidr:
    Description: CIDR block for the second public subnet
    Type: String
    Default: 10.0.3.0/24

  PrivateSubnet1Cidr:
    Description: CIDR block for the first private subnet
    Type: String
    Default: 10.0.4.0/27

  PrivateSubnet2Cidr:
    Description: CIDR block for the second private subnet
    Type: String
    Default: 10.0.5.0/27

  PrivateSubnet3Cidr:
    Description: CIDR block for the second private subnet
    Type: String
    Default: 10.0.6.0/27

  AvailabilityZone1:
    Description: First Availability Zone for subnets
    Type: String
    Default: us-east-1a

  AvailabilityZone2:
    Description: Second Availability Zone for subnets
    Type: String
    Default: us-east-1b

  AvailabilityZone3:
    Description: Second Availability Zone for subnets
    Type: String
    Default: us-east-1c 

  RedshiftVPCStackUrl:
    Type: String
    Description: 'Name of the VPC stack'

  #Redshift Serverless Parameters
  AdminUsername:
    Description: Master username for the Redshift Serverless database
    Type: String
    Default: admin
    AllowedPattern: '^[a-zA-Z][a-zA-Z0-9]*$'
    MinLength: 1
    MaxLength: 128
    ConstraintDescription: Must begin with a letter and be alphanumeric.

  AdminUserPassword:
    Description: Master password for the Redshift Serverless database
    Type: String
    NoEcho: true
    MinLength: 8
    MaxLength: 64
    Default: Admin1234567
    AllowedPattern: '[a-zA-Z0-9!@#$%^&*()_+=-]*'
    ConstraintDescription: Must contain alphanumeric characters and symbol.
    
  RedshiftServerlessStackUrl:
    Type: String
    Description: 'Name of the Redshift Serverless stack'  
 
  #DMS Parameters
  MySQLUsername:
    Type: String
    Default: admin
    NoEcho: true
  MySQLPassword:
    Type: String
    Default: Admin12345678
    NoEcho: true
  PostgreSQLUsername:
    Type: String
    Default: admins
    NoEcho: true
  PostgreSQLPassword:
    Type: String
    Default: Admin12345679
    NoEcho: true 

  DMSStackUrl:
    Type: String
    Description: 'Name of the DMS Stack Url'

  #Macie Parameters
  MacieStackUrl:
    Type: String
    Description: 'Name of the Macie Stack Url'
  
  #SQS Parameters
  SqsStackUrl:
    Type: String
    Description: 'Name of the SQS Stack Url'  


Resources:
  IAMRoleStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref IamRoleUrl
      QueueName: !GetAtt SqsStack.Outputs.QueueName

  s3buckets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref BucketFilePath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName

  GlueDatabase:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref GlueDBPath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName

  GlueCrawler:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref GlueCrawlerPath
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName
        DatabaseName: !GetAtt GlueDatabase.Outputs.DatabaseName
        S3TargetPath: !GetAtt s3buckets.Outputs.TrustedS3BucketName

  DynamoDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref DynamoDBStackUrl
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName
        ReadCapacityUnits: !Ref ReadCapacityUnits
        WriteCapacityUnits: !Ref WriteCapacityUnits

  RedshiftVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref RedshiftVPCStackUrl
      Parameters:
        VpcCidr: !Ref VpcCidr
        PublicSubnet1Cidr: !Ref PublicSubnet1Cidr
        PublicSubnet2Cidr: !Ref PublicSubnet2Cidr
        PublicSubnet3Cidr: !Ref PublicSubnet3Cidr
        PrivateSubnet1Cidr: !Ref PrivateSubnet1Cidr
        PrivateSubnet2Cidr: !Ref PrivateSubnet2Cidr
        PrivateSubnet3Cidr: !Ref PrivateSubnet3Cidr
        AvailabilityZone1: !Ref AvailabilityZone1
        AvailabilityZone2: !Ref AvailabilityZone2
        AvailabilityZone3: !Ref AvailabilityZone3  

  RedshiftServerlessStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref RedshiftServerlessStackUrl
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName
        AdminUsername: !Ref AdminUsername
        AdminUserPassword: !Ref AdminUserPassword
        VPCSecurityGroupIds: !Join [ ",", [!GetAtt RedshiftVPCStack.Outputs.SecurityGroupId]]
        SubnetIds: !Join [ ",", [ !GetAtt RedshiftVPCStack.Outputs.PublicSubnet1Id, !GetAtt RedshiftVPCStack.Outputs.PublicSubnet2Id, !GetAtt RedshiftVPCStack.Outputs.PublicSubnet3Id ]]        

  DMSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref DMSStackUrl
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName
        MySQLUsername: !Ref MySQLUsername
        MySQLPassword: !Ref MySQLPassword
        PostgreSQLUsername: !Ref PostgreSQLUsername
        PostgreSQLPassword: !Ref PostgreSQLPassword 
  
  MacieStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref MacieStackUrl

  SqsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref SqsStackUrl
      Parameters:
        EnvType: !Ref EnvType
        DomainName: !Ref DomainName   

Outputs:
  LandingBucketName:
    Description: The name of the Landing S3 bucket
    Value: !GetAtt s3buckets.Outputs.LandingBucketName
  RawS3BucketName:
    Description: The name of the Raw S3 bucket
    Value: !GetAtt s3buckets.Outputs.RawS3BucketName
  TrustedS3BucketName:
    Description: The name of the Trusted S3 bucket
    Value: !GetAtt s3buckets.Outputs.TrustedS3BucketName
  DatabaseName:
    Description: 'Name of the Glue Database'
    Value:  !GetAtt GlueDatabase.Outputs.DatabaseName
  CrawlerName:
    Description: 'Name of the created Glue Crawler'
    Value:  !GetAtt GlueCrawler.Outputs.CrawlerName
  TableName:
    Description: 'Name of the created DynamoDB table'
    Value: !GetAtt DynamoDBStack.Outputs.TableName
  RedshiftIamRoleName:
    Description: 'Name of the created Redshift IAM role'
    Value: !GetAtt IAMRoleStack.Outputs.RedshiftIamRoleName
  VpcId:
    Description: 'The VPC ID'
    Value: !GetAtt RedshiftVPCStack.Outputs.VpcId
  PublicSubnet1Id:
    Description: 'The ID of the first public subnet'
    Value: !GetAtt RedshiftVPCStack.Outputs.PublicSubnet1Id
  PublicSubnet2Id:
    Description: 'The ID of the second public subnet'
    Value: !GetAtt RedshiftVPCStack.Outputs.PublicSubnet2Id
  PublicSubnet3Id:
    Description: 'The ID of the third public subnet'
    Value: !GetAtt RedshiftVPCStack.Outputs.PublicSubnet3Id
  PrivateSubnet1Id:
    Description: 'The ID of the first private subnet'
    Value: !GetAtt RedshiftVPCStack.Outputs.PrivateSubnet1Id
  PrivateSubnet2Id:
    Description: 'The ID of the second private subnet'
    Value: !GetAtt RedshiftVPCStack.Outputs.PrivateSubnet2Id
  PrivateSubnet3Id:
    Description: 'The ID of the third private subnet'
    Value: !GetAtt RedshiftVPCStack.Outputs.PrivateSubnet3Id
  SecurityGroupId:
    Description: 'The ID of the Redshift Security Group'
    Value: !GetAtt RedshiftVPCStack.Outputs.SecurityGroupId
  WorkgroupEndpoint:
    Description: 'The endpoint of the Redshift Serverless workgroup'
    Value: !GetAtt RedshiftServerlessStack.Outputs.WorkgroupEndpoint
  QueueARN:
    Description: 'The ARN of the SQS Queue'
    Value: !GetAtt SqsStack.Outputs.QueueARN    
  QueueName:
    Description: 'The Name of the SQS Queue'
    Value: !GetAtt SqsStack.Outputs.QueueName                       


