AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for SNS Topic'

Parameters:
  EnvType:
    Type: String
    Default: "dev"
    Description: The environment type (e.g., prod, dev)

  DomainName:
    Type: String
    Description: The name of the domain

Resources:
  # SNS Topic  
  TpgSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Join:
            - "-"
            - [ !Ref DomainName, !Ref EnvType, "Topic"]

  # Email Subscription for the SNS Topic
  TpgSNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Sub '{{resolve:ssm:/sns/subscriberEmail}}'
      TopicArn: !Ref TpgSNSTopic

Outputs:
  TopicArn:
    Description: "SNS Topic ARN"
    Value: !Ref TpgSNSTopic
