Parameters:
  SubscriberEmail:
    Type: AWS::SSM::Parameter::Value<String>
    Description: "The email address to subscribe to the SNS topic"
    Default: "/sns/subscriberEmail"

Resources:
  # SNS Topic
  MySNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: MyTopic

  # IAM Role for SNS to allow Lambda to use the topic
  MySNSLambdaRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: MySNSLambdaRole
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Principal: 
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: MySNSPublishPolicy
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: Allow
                Action: 
                  - sns:Publish
                Resource: 
                  - Ref: MySNSTopic

  # Email Subscription for the SNS Topic
  MySNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Ref SubscriberEmail  # Replace with the email address for subscription
      TopicArn: 
        Ref: MySNSTopic

  # SNS Topic Policy to allow Lambda invocation
  SNSInvokeLambdaPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - Ref: MySNSTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sns:Publish
            Resource: 
              - Ref: MySNSTopic

Outputs:
  TopicArn:
    Description: "SNS Topic ARN"
    Value: !Ref MySNSTopic