AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for SNS Topic'

Parameters:
  EnvType:
    Type: String
    Default: "dev"
    Description: The environment type (e.g., prod, dev)

  DomainName:
    Type: String
    Description: The name of the domain

Resources:
  # SNS Topic  
  TpgSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Join:
            - "-"
            - [ !Ref DomainName, !Ref EnvType, "Topic"]

  # Email Subscription for the SNS Topic
  TpgSNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: !Sub '{{resolve:ssm:/sns/subscriberEmail}}'
      TopicArn: !Ref TpgSNSTopic

  # # SNS Topic Policy
  # SNSInvokeLambdaPolicy:
  #   Type: AWS::SNS::TopicPolicy
  #   Properties:
  #     Topics: 
  #       - !Ref TpgSNSTopic
  #     PolicyDocument:
  #       Id: SNSTopicPolicy
  #       Version: "2012-10-17"
  #       Statement:
  #         - Sid: AllowLambdaPublish
  #           Effect: Allow
  #           Principal:
  #             Service: "lambda.amazonaws.com"
  #           Action: "sns:Publish"
  #           Resource: !GetAtt TpgSNSTopic.TopicArn
  #         - Sid: AllowAccountAccess
  #           Effect: Allow
  #           Principal:
  #             AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
  #           Action:
  #             - "sns:Subscribe"
  #             - "sns:Publish"
  #           Resource: !GetAtt TpgSNSTopic.TopicArn

Outputs:
  TopicArn:
    Description: "SNS Topic ARN"
    Value: !Ref TpgSNSTopic
