AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create AWS DMS VPC and IAM role

Resources:
  ### IAM Role for DMS VPC Role ###
  DMSVPCRole:
    Type: AWS::IAM::Role
    Properties:
    RoleName: DMSVPCRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: dms.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole

  ### IAM Role for DMS ###
  DMSIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DMSRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: dms.amazonaws.com
            Action: sts:AssumeRole     
      Policies:
        - PolicyName: DMSAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:GetObject
                  - dms:CreateReplicationSubnetGroup
                  - dms:CreateReplicationTask
                  - dms:DescribeReplicationInstances
                  - dms:DescribeEndpoints
                  - dms:DescribeReplicationTasks
                  - dms:StartReplicationTask
                  - dms:StopReplicationTask
                  - dms:ModifyReplicationTask
                  - dms:DeleteReplicationTask
                  - dms:DescribeReplicationSubnetGroups
                  - dms:DescribeEventSubscriptions
                Resource: 
                  - "*"      

Outputs:
  DMSVPCRole:
    Description: 'Name of the created DMS VPC role'
    Value: !Ref DMSVPCRole
    Export:
      Name: DMSVPCRole 
  DMSIAMRole:
    Description: 'Name of the created DMS IAM role'
    Value: !Ref DMSIAMRole
    Export:
      Name: DMSIAMRole           