AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create AWS DMS VPC role

Resources:
  ### IAM Role for DMS VPC Role ###
  DMSVPCRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: dms-vpc-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: dms.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonDMSVPCManagementRole

Outputs:
  DMSVPCRole:
    Description: 'Name of the created DMS VPC role'
    Value: !Ref DMSVPCRole
    Export:
      Name: DMSVPCRole         