AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create IAM roles

Parameters:
  EnvType:
    Type: String
    Default: "dev"
    Description: The environment type (e.g., prod, dev)
  DomainName:
    Type: String
    Description: The name of the domain

Resources:
#Redshift Role
  RedshiftServerlessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvType}-${DomainName}-redshift-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: redshift-serverless.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonRedshiftAllCommandsFullAccess
      Policies:
        - PolicyName: RedshiftServerlessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:PutObject'
                Resource: '*'

  ### IAM Role for DMS ###
  DMSIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvType}-${DomainName}-dms-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: dms.amazonaws.com
            Action: sts:AssumeRole     
      Policies:
        - PolicyName: DMSAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:GetObject
                  - dms:CreateReplicationSubnetGroup
                  - dms:CreateReplicationTask
                  - dms:DescribeReplicationInstances
                  - dms:DescribeEndpoints
                  - dms:DescribeReplicationTasks
                  - dms:StartReplicationTask
                  - dms:StopReplicationTask
                  - dms:ModifyReplicationTask
                  - dms:DeleteReplicationTask
                  - dms:DescribeReplicationSubnetGroups
                  - dms:DescribeEventSubscriptions
                Resource: 
                  - "*"

### IAM Role for SQS ###     
  MyQueueIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvType}-${DomainName}-sqs-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"  # Replace this with the service or entity that will assume the role
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: SQSAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:GetQueueUrl
                  - sqs:ListQueues
                Resource: 
                   - "*"
### IAM Role for Glue Job ### 
  GlueJobRole:                
    Type: AWS::IAM::Role
    Properties:
      RoleName: 
         Fn::Join:
          - "-"
          - [ "sandbox", !Ref DomainName, !Ref EnvType, "gluejob-role"]       
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource: '*'
        - PolicyName: CloudwatchAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*' 

Outputs: 
  DMSIAMRole:
    Description: 'Name of the created DMS IAM role'
    Value: !Ref DMSIAMRole
    Export:
      Name: DMSIAMRole
  RedshiftIamRoleName:
    Description: 'Name of the created Redshift role'
    Value: !Ref RedshiftServerlessRole
  RedshiftIamRoleArn:
    Description: 'ARN of the Redshift Serverless IAM Role'
    Value: !GetAtt RedshiftServerlessRole.Arn
  MyQueueIAMRole:
    Description: 'Name of the MyQueue IAM Role'
    Value: !Ref MyQueueIAMRole
  GlueJobRoleArn:
    Description: 'Name of the Glue Job Role'
    Value: !GetAtt GlueJobRole.Arn           