AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create IAM roles

Resources:
#Redshift Role
  RedshiftServerlessReadOnlyRole:
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: "RedshiftServerlessReadOnlyRole"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "redshift.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "RedshiftServerlessReadOnlyPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "redshift-serverless:GetWorkgroup"
                  - "redshift-serverless:ListWorkgroups"
                  - "redshift-serverless:GetNamespace"
                  - "redshift-serverless:ListNamespaces"
                  - "redshift-serverless:GetSnapshot"
                  - "redshift-serverless:ListSnapshots"
                  - "redshift-serverless:GetUsageLimit"
                  - "redshift-serverless:ListUsageLimits"
                  - "redshift-serverless:GetTableRestoreStatus"
                  - "redshift-serverless:ListTableRestoreStatuses"
                  - "redshift-serverless:GetEndpointAccess"
                  - "redshift-serverless:ListEndpointAccess"
                  - "redshift:GetClusterCredentials"
                  - "redshift:DescribeClusters"
                  - "redshift:DescribeTables"
                  - "redshift:DescribeDatabase"
                  - "redshift:ExecuteQuery"
                Resource: "*"

  ### IAM Role for DMS ###
  DMSIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: DMSRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: dms.amazonaws.com
            Action: sts:AssumeRole     
      Policies:
        - PolicyName: DMSAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:PutObject
                  - s3:GetObject
                  - dms:CreateReplicationSubnetGroup
                  - dms:CreateReplicationTask
                  - dms:DescribeReplicationInstances
                  - dms:DescribeEndpoints
                  - dms:DescribeReplicationTasks
                  - dms:StartReplicationTask
                  - dms:StopReplicationTask
                  - dms:ModifyReplicationTask
                  - dms:DeleteReplicationTask
                  - dms:DescribeReplicationSubnetGroups
                  - dms:DescribeEventSubscriptions
                Resource: 
                  - "*"


Outputs: 
  DMSIAMRole:
    Description: 'Name of the created DMS IAM role'
    Value: !Ref DMSIAMRole
    Export:
      Name: DMSIAMRole
  RedshiftIamRoleName:
    Description: 'Name of the created Redshift role'
    Value: !Ref RedshiftServerlessReadOnlyRole       