version: 0.2
phases:
  build:
    commands:
      - |
        echo Build started on `date`
        filename="sample_config_file.txt"
        file=$CODEBUILD_SRC_DIR/config_files/"${filename}"
        echo $file
        echo Printing env variables
        echo "Environment: ${env}"
        echo "Domain: ${domain}"
        KEY="${domain}_${env}"
        echo "${KEY}"
        VALUE=$(grep "^${KEY}=" "$file" | sed -e "s/^${KEY}=//")
        if [ -z "$VALUE" ]; then
        echo "Key '$KEY' not found in $file"
        else echo "The value for '$KEY' is '$VALUE'"
        fi
        cfnfilename="main.yaml"
        cfnfile=$CODEBUILD_SRC_DIR/cfn/"${cfnfilename}"
        echo $cfnfile
        iamrolefilename="iamRoles.yaml"
        iamrolefile=$CODEBUILD_SRC_DIR/cfn/iam_role/"${iamrolefilename}"
        echo $iamrolefile
        bucketfilename="bucket.yaml"
        bucketfile=$CODEBUILD_SRC_DIR/cfn/"${bucketfilename}"
        echo $bucketfile
        gluedbfilename="glue_database.yaml"
        gluedbfile=$CODEBUILD_SRC_DIR/cfn/"${gluedbfilename}"
        echo $gluedbfile
        gluecrawlerfilename="glue_crawler.yaml"
        gluecrawlerfile=$CODEBUILD_SRC_DIR/cfn/"${gluecrawlerfilename}"
        echo $gluecrawlerfile
        dynamodbfilename="dynamodb.yaml"
        dynamodbfile=$CODEBUILD_SRC_DIR/cfn/"${dynamodbfilename}"
        echo $dynamodbfile
        redshiftvpcfilename="redshiftVPCSubnet.yaml"
        redshiftvpcfile=$CODEBUILD_SRC_DIR/cfn/"${redshiftvpcfilename}"
        echo $redshiftvpcfile
        redshiftServerlessfilename="redshiftServerless.yaml"
        redshiftServerlessfile=$CODEBUILD_SRC_DIR/cfn/"${redshiftServerlessfilename}"
        echo $redshiftServerlessfile
        dmsfilename="dms.yaml"
        dmsfile=$CODEBUILD_SRC_DIR/cfn/"${dmsfilename}"
        echo $dmsfile
        maciefilename="macie.yaml"
        maciefile=$CODEBUILD_SRC_DIR/cfn/"${maciefilename}"
        echo $maciefile
        sqsfilename="sqs.yaml"
        sqsfile=$CODEBUILD_SRC_DIR/cfn/"${sqsfilename}"
        echo $sqsfile
        gluejobfilename="glue_job.yaml"
        gluejobfile=$CODEBUILD_SRC_DIR/cfn/"${gluejobfilename}"
        echo $gluejobfile 
        dbtredshiftfilename="dbt_redshift_ecr.yaml"
        dbtredshiftfile=$CODEBUILD_SRC_DIR/cfn/"${dbtredshiftfilename}"
        echo $dbtredshiftfile
        snsfilename="sns.yaml"
        snsfile=$CODEBUILD_SRC_DIR/cfn/"${snsfilename}"
        echo $snsfile       
        aws s3 cp $iamrolefile s3://tpg-my-bucket/cicd-files/
        aws s3 cp $bucketfile s3://tpg-my-bucket/cicd-files/
        aws s3 cp $gluedbfile s3://tpg-my-bucket/cicd-files/
        aws s3 cp $gluecrawlerfile s3://tpg-my-bucket/cicd-files/
        aws s3 cp $dynamodbfile s3://tpg-my-bucket/cicd-files/
        aws s3 cp $redshiftvpcfile s3://tpg-my-bucket/cicd-files/
        aws s3 cp $redshiftServerlessfile s3://tpg-my-bucket/cicd-files/
        aws s3 cp $dmsfile s3://tpg-my-bucket/cicd-files/
        aws s3 cp $maciefile s3://tpg-my-bucket/cicd-files/
        aws s3 cp $sqsfile s3://tpg-my-bucket/cicd-files/
        aws s3 cp $gluejobfile s3://tpg-my-bucket/cicd-files/  
        aws s3 cp $dbtredshiftfile s3://tpg-my-bucket/cicd-files/
        aws s3 cp $snsfile s3://tpg-my-bucket/cicd-files/      
        iamroleurl=https://s3.amazonaws.com/tpg-my-bucket/cicd-files/iamRoles.yaml
        bucketurl=https://s3.amazonaws.com/tpg-my-bucket/cicd-files/bucket.yaml
        GlueDBurl=https://s3.amazonaws.com/tpg-my-bucket/cicd-files/glue_database.yaml
        GlueCrawlerurl=https://s3.amazonaws.com/tpg-my-bucket/cicd-files/glue_crawler.yaml
        dynamodburl=https://s3.amazonaws.com/tpg-my-bucket/cicd-files/dynamodb.yaml
        redshiftvpcurl=https://s3.amazonaws.com/tpg-my-bucket/cicd-files/redshiftVPCSubnet.yaml
        redshiftserverlessurl=https://s3.amazonaws.com/tpg-my-bucket/cicd-files/redshiftServerless.yaml
        dmsurl=https://s3.amazonaws.com/tpg-my-bucket/cicd-files/dms.yaml
        macieurl=https://s3.amazonaws.com/tpg-my-bucket/cicd-files/macie.yaml
        sqsurl=https://s3.amazonaws.com/tpg-my-bucket/cicd-files/sqs.yaml
        gluejoburl=https://s3.amazonaws.com/tpg-my-bucket/cicd-files/glue_job.yaml
        dbtredshifturl=https://s3.amazonaws.com/tpg-my-bucket/cicd-files/dbt_redshift_ecr.yaml
        snsurl=https://s3.amazonaws.com/tpg-my-bucket/cicd-files/sns.yaml
        aws cloudformation deploy \
          --template-file $cfnfile \
          --stack-name tpg-stack \
          --parameter-overrides EnvType="${env}" DomainName="${domain}" IamRoleUrl="${iamroleurl}" SnsStackUrl="${snsurl}" \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
  post_build:
    commands:
      - aws cloudformation describe-stack-events --stack-name tpg-stack
      - echo Build complete
